[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1"
once_cell = "1.17"
log = "0.4"
js-sys = "0.3"
serde = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
yew = "0.19"
wasm-logger = "0.2"
yew-router = "0.16"
