name: App test

on:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  app-changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          app:
            - 'app/**'

  run-app-tests:
    runs-on: ubuntu-latest
    env:
      cache_id: app
    needs: app-changes
    if: ${{ needs.app-changes.outputs.app == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: ${{ env.cache_id }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUSTC_HASH }}

      - name: test-app
        working-directory: ./app
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test -- --nocapture --test-threads 1
